name: pandoc_jaspr
description: Converts Pandoc JSON AST into Jaspr Component trees for LaTeX-driven Jaspr sites.
version: 1.0.0
repository: https://github.com/hugo-bluecorn/pandoc_jaspr
issue_tracker: https://github.com/hugo-bluecorn/pandoc_jaspr/issues

environment:
  sdk: ^3.11.5

# Add regular dependencies here.
dependencies:
  jaspr: ^0.23.1
  jaspr_content: ^0.5.2
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
